import type { Building, BuildingType } from '../types'

export interface BuildingPreset {
  label: string
  icon: string
  defaultParams: Record<string, number>
  paramLabels: Record<string, string>
  defaultColor?: string
}

export const BUILDING_PRESETS: Record<BuildingType, BuildingPreset> = {
  box: {
    label: '长方体',
    icon: 'box',
    defaultParams: { width: 20, depth: 15, height: 50 },
    paramLabels: { width: '宽度', depth: '进深', height: '高度' },
  },
  cylinder: {
    label: '圆柱体',
    icon: 'cylinder',
    defaultParams: { radius: 10, height: 40, segments: 32 },
    paramLabels: { radius: '半径', height: '高度', segments: '分段数' },
  },
  prism: {
    label: '棱柱体',
    icon: 'prism',
    defaultParams: { sides: 6, radius: 12, height: 35 },
    paramLabels: { sides: '边数', radius: '外接半径', height: '高度' },
  },
  'l-shape': {
    label: 'L 形',
    icon: 'l-shape',
    defaultParams: { wing1Length: 30, wing2Length: 25, width: 12, height: 40 },
    paramLabels: { wing1Length: '翼1长度', wing2Length: '翼2长度', width: '宽度', height: '高度' },
  },
  'u-shape': {
    label: 'U 形',
    icon: 'u-shape',
    defaultParams: { wing1Length: 25, wing2Length: 25, backLength: 30, width: 10, height: 35 },
    paramLabels: { wing1Length: '翼1长度', wing2Length: '翼2长度', backLength: '底边长', width: '宽度', height: '高度' },
  },
  't-shape': {
    label: 'T 形',
    icon: 't-shape',
    defaultParams: { crossLength: 40, stemLength: 30, width: 12, height: 45 },
    paramLabels: { crossLength: '横翼长度', stemLength: '纵翼长度', width: '宽度', height: '高度' },
  },
  stepped: {
    label: '阶梯退台',
    icon: 'stepped',
    defaultParams: { baseWidth: 30, baseDepth: 25, levels: 3, stepback: 4, levelHeight: 15 },
    paramLabels: { baseWidth: '底部宽度', baseDepth: '底部进深', levels: '层数', stepback: '每层缩进', levelHeight: '层高' },
  },
  'podium-tower': {
    label: '裙楼+塔楼',
    icon: 'podium-tower',
    defaultParams: { podiumWidth: 40, podiumDepth: 30, podiumHeight: 15, towerWidth: 18, towerDepth: 15, towerHeight: 60 },
    paramLabels: { podiumWidth: '裙楼宽', podiumDepth: '裙楼深', podiumHeight: '裙楼高', towerWidth: '塔楼宽', towerDepth: '塔楼深', towerHeight: '塔楼高' },
  },
  dome: {
    label: '穹顶',
    icon: 'dome',
    defaultParams: { radius: 12, cylinderHeight: 20 },
    paramLabels: { radius: '半径', cylinderHeight: '柱体高度' },
  },
  'gable-roof': {
    label: '坡屋顶',
    icon: 'gable-roof',
    defaultParams: { width: 20, depth: 25, wallHeight: 12, ridgeHeight: 8 },
    paramLabels: { width: '宽度', depth: '进深', wallHeight: '墙高', ridgeHeight: '屋脊高' },
  },
  road: {
    label: '道路',
    icon: 'road',
    defaultParams: { length: 80, width: 12 },
    paramLabels: { length: '长度', width: '宽度' },
    defaultColor: '#708090',
  },
  'green-belt': {
    label: '绿化带',
    icon: 'green-belt',
    defaultParams: { length: 60, width: 6, height: 1.5 },
    paramLabels: { length: '长度', width: '宽度', height: '高度' },
    defaultColor: '#4CAF50',
  },
  tree: {
    label: '树木',
    icon: 'tree',
    defaultParams: { trunkHeight: 5, trunkRadius: 0.8, canopyRadius: 5, canopyHeight: 8 },
    paramLabels: { trunkHeight: '树干高', trunkRadius: '树干半径', canopyRadius: '树冠半径', canopyHeight: '树冠高' },
    defaultColor: '#2E7D32',
  },

  'ai-circular': {
    label: 'AI 圆形建筑',
    icon: 'ai-circular',
    defaultParams: { radius: 15, segments: 48, levels: 3 },
    paramLabels: { radius: '半径', segments: '分段数', levels: '层数' },
  },
  'ai-complex': {
    label: 'AI 复杂建筑',
    icon: 'ai-complex',
    defaultParams: { levels: 3 },
    paramLabels: { levels: '层数' },
  },
  glb: {
    label: 'GLB 模型',
    icon: 'glb',
    defaultParams: { scale: 1 },
    paramLabels: { scale: '缩放' },
  },
  'girder-bridge': {
    label: '梁式桥',
    icon: 'girder-bridge',
    defaultParams: {
      length: 120,
      width: 20,
      deckThickness: 1.5,
      deckHeight: 8,
      pierCount: 3,
      pierWidth: 4,
      pierDepth: 6,
      girderHeight: 2,
    },
    paramLabels: {
      length: '桥长',
      width: '桥宽',
      deckThickness: '桥面厚度',
      deckHeight: '桥面高度',
      pierCount: '桥墩数量',
      pierWidth: '桥墩宽',
      pierDepth: '桥墩深',
      girderHeight: '梁高',
    },
    defaultColor: '#808080',
  },
  'arch-bridge': {
    label: '拱式桥',
    icon: 'arch-bridge',
    defaultParams: {
      length: 150,
      width: 20,
      deckThickness: 1.5,
      deckHeight: 12,
      archHeight: 25,
      archRadius: 60,
      pierWidth: 5,
      pierDepth: 8,
      spandrelCount: 6,
    },
    paramLabels: {
      length: '桥长',
      width: '桥宽',
      deckThickness: '桥面厚度',
      deckHeight: '桥面高度',
      archHeight: '拱高',
      archRadius: '拱半径',
      pierWidth: '桥墩宽',
      pierDepth: '桥墩深',
      spandrelCount: '拱上立柱数',
    },
    defaultColor: '#A0522D',
  },
  'suspension-bridge': {
    label: '悬索桥',
    icon: 'suspension-bridge',
    defaultParams: {
      mainSpan: 200,
      sideSpan: 80,
      width: 25,
      deckThickness: 2,
      deckHeight: 15,
      towerHeight: 60,
      towerWidth: 8,
      towerDepth: 12,
      mainCableHeight: 40,
      hangerCount: 20,
    },
    paramLabels: {
      mainSpan: '主跨长度',
      sideSpan: '边跨长度',
      width: '桥宽',
      deckThickness: '桥面厚度',
      deckHeight: '桥面高度',
      towerHeight: '桥塔高度',
      towerWidth: '桥塔宽',
      towerDepth: '桥塔深',
      mainCableHeight: '主缆高度',
      hangerCount: '吊杆数量',
    },
    defaultColor: '#4682B4',
  },
  'cable-stayed-bridge': {
    label: '斜拉桥',
    icon: 'cable-stayed-bridge',
    defaultParams: {
      mainSpan: 180,
      sideSpan: 70,
      width: 25,
      deckThickness: 2,
      deckHeight: 15,
      towerHeight: 50,
      towerWidth: 6,
      towerDepth: 10,
      cableCount: 12,
      cableFanAngle: 30,
    },
    paramLabels: {
      mainSpan: '主跨长度',
      sideSpan: '边跨长度',
      width: '桥宽',
      deckThickness: '桥面厚度',
      deckHeight: '桥面高度',
      towerHeight: '桥塔高度',
      towerWidth: '桥塔宽',
      towerDepth: '桥塔深',
      cableCount: '拉索数量',
      cableFanAngle: '拉索扇角',
    },
    defaultColor: '#5F9EA0',
  },
  'basketball-court': {
    label: '篮球场',
    icon: 'basketball-court',
    defaultParams: {
      length: 28,
      width: 15,
      floorThickness: 0.2,
      poleHeight: 4,
      backboardWidth: 1.8,
      backboardHeight: 1.05,
    },
    paramLabels: {
      length: '场地长度',
      width: '场地宽度',
      floorThickness: '地板厚度',
      poleHeight: '篮架高度',
      backboardWidth: '篮板宽度',
      backboardHeight: '篮板高度',
    },
    defaultColor: '#D2B48C',
  },
  'football-field': {
    label: '足球场',
    icon: 'football-field',
    defaultParams: {
      length: 105,
      width: 68,
      floorThickness: 0.2,
      goalHeight: 2.44,
      goalWidth: 7.32,
    },
    paramLabels: {
      length: '场地长度',
      width: '场地宽度',
      floorThickness: '草坪厚度',
      goalHeight: '球门高度',
      goalWidth: '球门宽度',
    },
    defaultColor: '#228B22',
  },
  'tennis-court': {
    label: '网球场',
    icon: 'tennis-court',
    defaultParams: {
      length: 23.77,
      width: 10.97,
      singleWidth: 8.23,
      floorThickness: 0.2,
      netHeight: 0.914,
    },
    paramLabels: {
      length: '场地长度',
      width: '双打宽度',
      singleWidth: '单打宽度',
      floorThickness: '场地厚度',
      netHeight: '球网高度',
    },
    defaultColor: '#4169E1',
  },
  'gymnasium': {
    label: '体育馆',
    icon: 'gymnasium',
    defaultParams: {
      length: 80,
      width: 60,
      height: 25,
      wallThickness: 1.5,
      roofHeight: 12,
      entranceWidth: 12,
      entranceHeight: 6,
    },
    paramLabels: {
      length: '建筑长度',
      width: '建筑宽度',
      height: '建筑高度',
      wallThickness: '墙体厚度',
      roofHeight: '屋顶高度',
      entranceWidth: '入口宽度',
      entranceHeight: '入口高度',
    },
    defaultColor: '#F5F5DC',
  },

  // ─── 车辆类型预设 ──────────────────────────────────────────────
  'car': {
    label: '小汽车',
    icon: 'car',
    defaultParams: {
      length: 4.5,
      width: 1.8,
      height: 1.5,
      wheelRadius: 0.35,
      wheelWidth: 0.2,
    },
    paramLabels: {
      length: '车身长度',
      width: '车身宽度',
      height: '车身高度',
      wheelRadius: '车轮半径',
      wheelWidth: '车轮宽度',
    },
    defaultColor: '#E53935',
  },
  'suv': {
    label: 'SUV',
    icon: 'suv',
    defaultParams: {
      length: 4.8,
      width: 1.9,
      height: 1.7,
      wheelRadius: 0.4,
      wheelWidth: 0.25,
      groundClearance: 0.2,
    },
    paramLabels: {
      length: '车身长度',
      width: '车身宽度',
      height: '车身高度',
      wheelRadius: '车轮半径',
      wheelWidth: '车轮宽度',
      groundClearance: '离地间隙',
    },
    defaultColor: '#1E88E5',
  },
  'van': {
    label: '货车',
    icon: 'van',
    defaultParams: {
      length: 5.5,
      width: 2.0,
      height: 2.2,
      wheelRadius: 0.38,
      wheelWidth: 0.22,
      cargoHeight: 1.5,
    },
    paramLabels: {
      length: '车身长度',
      width: '车身宽度',
      height: '车身高度',
      wheelRadius: '车轮半径',
      wheelWidth: '车轮宽度',
      cargoHeight: '货箱高度',
    },
    defaultColor: '#757575',
  },
  'truck': {
    label: '卡车',
    icon: 'truck',
    defaultParams: {
      length: 12.0,
      width: 2.5,
      height: 3.5,
      wheelRadius: 0.5,
      wheelWidth: 0.3,
      cabLength: 3.0,
      cargoLength: 7.0,
      cargoHeight: 2.5,
    },
    paramLabels: {
      length: '车身长度',
      width: '车身宽度',
      height: '车身高度',
      wheelRadius: '车轮半径',
      wheelWidth: '车轮宽度',
      cabLength: '驾驶室长度',
      cargoLength: '货箱长度',
      cargoHeight: '货箱高度',
    },
    defaultColor: '#FDD835',
  },
  'bus': {
    label: '巴士',
    icon: 'bus',
    defaultParams: {
      length: 10.0,
      width: 2.5,
      height: 3.2,
      wheelRadius: 0.45,
      wheelWidth: 0.28,
      windowHeight: 0.8,
      windowCount: 8,
    },
    paramLabels: {
      length: '车身长度',
      width: '车身宽度',
      height: '车身高度',
      wheelRadius: '车轮半径',
      wheelWidth: '车轮宽度',
      windowHeight: '窗户高度',
      windowCount: '窗户数量',
    },
    defaultColor: '#43A047',
  },
  'city-bus': {
    label: '公交车',
    icon: 'city-bus',
    defaultParams: {
      length: 12.0,
      width: 2.5,
      height: 3.0,
      wheelRadius: 0.45,
      wheelWidth: 0.28,
      windowHeight: 0.9,
      windowCount: 10,
      doorWidth: 1.2,
    },
    paramLabels: {
      length: '车身长度',
      width: '车身宽度',
      height: '车身高度',
      wheelRadius: '车轮半径',
      wheelWidth: '车轮宽度',
      windowHeight: '窗户高度',
      windowCount: '窗户数量',
      doorWidth: '车门宽度',
    },
    defaultColor: '#FF6F00',
  },
  'train': {
    label: '火车',
    icon: 'train',
    defaultParams: {
      length: 25.0,
      width: 3.0,
      height: 4.0,
      wheelRadius: 0.5,
      wheelWidth: 0.25,
      carriageCount: 3,
      carriageLength: 7.0,
      windowHeight: 1.2,
      windowCount: 6,
    },
    paramLabels: {
      length: '列车长度',
      width: '车身宽度',
      height: '车身高度',
      wheelRadius: '车轮半径',
      wheelWidth: '车轮宽度',
      carriageCount: '车厢数量',
      carriageLength: '车厢长度',
      windowHeight: '窗户高度',
      windowCount: '每节窗户数',
    },
    defaultColor: '#C62828',
  },

  // ─── 船舶类型预设 ──────────────────────────────────────────────
  'cargo-ship': {
    label: '货轮',
    icon: 'cargo-ship',
    defaultParams: {
      length: 120.0,
      width: 20.0,
      height: 25.0,
      draft: 5.0,
      holdLength: 80.0,
      holdWidth: 16.0,
      holdHeight: 8.0,
      superstructureHeight: 12.0,
    },
    paramLabels: {
      length: '船长',
      width: '船宽',
      height: '总高度',
      draft: '吃水深度',
      holdLength: '货舱长度',
      holdWidth: '货舱宽度',
      holdHeight: '货舱高度',
      superstructureHeight: '上层建筑高度',
    },
    defaultColor: '#546E7A',
  },
  'container-ship': {
    label: '集装箱轮船',
    icon: 'container-ship',
    defaultParams: {
      length: 200.0,
      width: 30.0,
      height: 40.0,
      draft: 8.0,
      deckLength: 150.0,
      containerRows: 8,
      containerStacks: 6,
      superstructureHeight: 15.0,
    },
    paramLabels: {
      length: '船长',
      width: '船宽',
      height: '总高度',
      draft: '吃水深度',
      deckLength: '甲板长度',
      containerRows: '集装箱排数',
      containerStacks: '集装箱层数',
      superstructureHeight: '上层建筑高度',
    },
    defaultColor: '#37474F',
  },
  'cruise-ship': {
    label: '游轮',
    icon: 'cruise-ship',
    defaultParams: {
      length: 180.0,
      width: 28.0,
      height: 45.0,
      draft: 7.0,
      deckCount: 8,
      deckHeight: 2.5,
      funnelHeight: 10.0,
      poolLength: 15.0,
    },
    paramLabels: {
      length: '船长',
      width: '船宽',
      height: '总高度',
      draft: '吃水深度',
      deckCount: '甲板层数',
      deckHeight: '每层高度',
      funnelHeight: '烟囱高度',
      poolLength: '泳池长度',
    },
    defaultColor: '#ECEFF1',
  },
  'pleasure-boat': {
    label: '游船',
    icon: 'pleasure-boat',
    defaultParams: {
      length: 8.0,
      width: 2.5,
      height: 3.5,
      draft: 0.5,
      cabinHeight: 1.5,
      cabinWidth: 2.0,
      deckHeight: 0.3,
    },
    paramLabels: {
      length: '船长',
      width: '船宽',
      height: '总高度',
      draft: '吃水深度',
      cabinHeight: '船舱高度',
      cabinWidth: '船舱宽度',
      deckHeight: '甲板高度',
    },
    defaultColor: '#B3E5FC',
  },

  // ─── 交通设施类型预设 ──────────────────────────────────────────────
  'traffic-light': {
    label: '红绿灯',
    icon: 'traffic-light',
    defaultParams: {
      poleHeight: 3.5,
      poleRadius: 0.08,
      headWidth: 0.6,
      headHeight: 1.2,
      headDepth: 0.3,
      lightRadius: 0.15,
      armLength: 2.0,
      directionCount: 2,
    },
    paramLabels: {
      poleHeight: '杆高',
      poleRadius: '杆半径',
      headWidth: '灯箱宽度',
      headHeight: '灯箱高度',
      headDepth: '灯箱深度',
      lightRadius: '灯珠半径',
      armLength: '悬臂长度',
      directionCount: '方向数量',
    },
    defaultColor: '#4A4A4A',
  },
  'street-sign': {
    label: '路牌',
    icon: 'street-sign',
    defaultParams: {
      poleHeight: 2.5,
      poleRadius: 0.06,
      signWidth: 1.2,
      signHeight: 0.8,
      signThickness: 0.05,
      signCount: 2,
      signSpacing: 0.15,
      armLength: 1.5,
    },
    paramLabels: {
      poleHeight: '杆高',
      poleRadius: '杆半径',
      signWidth: '牌面宽度',
      signHeight: '牌面高度',
      signThickness: '牌面厚度',
      signCount: '牌面数量',
      signSpacing: '牌面间距',
      armLength: '悬臂长度',
    },
    defaultColor: '#2E7D32',
  },
  'street-lamp': {
    label: '路灯',
    icon: 'street-lamp',
    defaultParams: {
      poleHeight: 6.0,
      poleRadius: 0.08,
      armLength: 1.5,
      armHeightOffset: 0.5,
      lampWidth: 0.8,
      lampHeight: 0.3,
      lampDepth: 0.5,
      lightEmission: 1.0,
    },
    paramLabels: {
      poleHeight: '杆高',
      poleRadius: '杆半径',
      armLength: '悬臂长度',
      armHeightOffset: '悬臂高度偏移',
      lampWidth: '灯座宽度',
      lampHeight: '灯座高度',
      lampDepth: '灯座深度',
      lightEmission: '发光强度',
    },
    defaultColor: '#607D8B',
  },
}

const COLORS = [
  '#6B8EC2', '#8FC1A9', '#D4A574', '#C2847A', '#9B8EC2',
  '#7ABFBF', '#C2B06B', '#B07AAB', '#7A9FC2', '#A0C27A',
]

let colorIndex = 0

export function getDefaultParams(type: BuildingType): Record<string, number> {
  return { ...BUILDING_PRESETS[type].defaultParams }
}

export function createBuilding(type: BuildingType, position: [number, number] = [0, 0]): Building {
  const preset = BUILDING_PRESETS[type]
  const color = preset.defaultColor ?? COLORS[colorIndex % COLORS.length]
  colorIndex++
  return {
    id: `building-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    name: `${BUILDING_PRESETS[type].label} ${colorIndex}`,
    type,
    params: getDefaultParams(type),
    position,
    rotation: 0,
    color,
    baseHeight: 0,
  }
}
