import type { BuildingTemplate } from '../types'

export const BUILDING_TEMPLATES: BuildingTemplate[] = [
  {
    id: 'chinese-pavilion-hexagonal',
    name: '六角亭',
    category: '中式古建',
    description: '传统中式六角亭，带有飞檐和柱子',
    icon: 'pavilion',
    buildings: [
      {
        type: 'ai-circular',
        params: {
          segments: 48,
          levelCount: 2,
          level_0_height: 4,
          level_0_radius: 8,
          level_0_roofType: 1,
          level_0_overhang: 3,
          level_1_height: 0.5,
          level_1_radius: 0.5,
          level_1_roofType: 0,
          level_1_overhang: 0,
        },
        position: [0, 0],
        rotation: 0,
        color: '#8B4513',
      },
      {
        type: 'cylinder',
        params: { radius: 0.4, height: 4, segments: 16 },
        position: [6, 0],
        rotation: 0,
        color: '#A0522D',
      },
      {
        type: 'cylinder',
        params: { radius: 0.4, height: 4, segments: 16 },
        position: [-6, 0],
        rotation: 0,
        color: '#A0522D',
      },
      {
        type: 'cylinder',
        params: { radius: 0.4, height: 4, segments: 16 },
        position: [3, 5.196],
        rotation: 0,
        color: '#A0522D',
      },
      {
        type: 'cylinder',
        params: { radius: 0.4, height: 4, segments: 16 },
        position: [-3, 5.196],
        rotation: 0,
        color: '#A0522D',
      },
      {
        type: 'cylinder',
        params: { radius: 0.4, height: 4, segments: 16 },
        position: [3, -5.196],
        rotation: 0,
        color: '#A0522D',
      },
      {
        type: 'cylinder',
        params: { radius: 0.4, height: 4, segments: 16 },
        position: [-3, -5.196],
        rotation: 0,
        color: '#A0522D',
      },
    ],
  },
  {
    id: 'chinese-pavilion-square',
    name: '四方亭',
    category: '中式古建',
    description: '传统中式四方亭，简洁典雅',
    icon: 'pavilion-square',
    buildings: [
      {
        type: 'ai-complex',
        params: {
          levelCount: 2,
          level_0_height: 4,
          level_0_width: 12,
          level_0_depth: 12,
          level_0_roofType: 1,
          level_0_overhang: 2.5,
          level_1_height: 0.3,
          level_1_width: 1,
          level_1_depth: 1,
          level_1_roofType: 0,
          level_1_overhang: 0,
        },
        position: [0, 0],
        rotation: 0,
        color: '#8B4513',
      },
      {
        type: 'cylinder',
        params: { radius: 0.35, height: 4, segments: 12 },
        position: [5, 5],
        rotation: 0,
        color: '#A0522D',
      },
      {
        type: 'cylinder',
        params: { radius: 0.35, height: 4, segments: 12 },
        position: [-5, 5],
        rotation: 0,
        color: '#A0522D',
      },
      {
        type: 'cylinder',
        params: { radius: 0.35, height: 4, segments: 12 },
        position: [5, -5],
        rotation: 0,
        color: '#A0522D',
      },
      {
        type: 'cylinder',
        params: { radius: 0.35, height: 4, segments: 12 },
        position: [-5, -5],
        rotation: 0,
        color: '#A0522D',
      },
    ],
  },
  {
    id: 'chinese-tower',
    name: '中式塔楼',
    category: '中式古建',
    description: '多层中式塔楼，层层飞檐',
    icon: 'tower',
    buildings: [
      {
        type: 'ai-circular',
        params: {
          segments: 48,
          levelCount: 5,
          level_0_height: 5,
          level_0_radius: 10,
          level_0_roofType: 1,
          level_0_overhang: 2,
          level_1_height: 4,
          level_1_radius: 8,
          level_1_roofType: 1,
          level_1_overhang: 1.8,
          level_2_height: 4,
          level_2_radius: 6,
          level_2_roofType: 1,
          level_2_overhang: 1.5,
          level_3_height: 4,
          level_3_radius: 4,
          level_3_roofType: 1,
          level_3_overhang: 1.2,
          level_4_height: 3,
          level_4_radius: 1.5,
          level_4_roofType: 2,
          level_4_overhang: 0,
        },
        position: [0, 0],
        rotation: 0,
        color: '#8B4513',
      },
    ],
  },
  {
    id: 'modern-glass-office',
    name: '玻璃幕墙办公楼',
    category: '现代玻璃幕墙',
    description: '现代风格玻璃幕墙办公楼，简洁大气',
    icon: 'glass-building',
    buildings: [
      {
        type: 'podium-tower',
        params: {
          podiumWidth: 50,
          podiumDepth: 30,
          podiumHeight: 12,
          towerWidth: 30,
          towerDepth: 20,
          towerHeight: 80,
        },
        position: [0, 0],
        rotation: 0,
        color: '#5DADE2',
      },
    ],
  },
  {
    id: 'modern-glass-tower',
    name: '玻璃塔楼',
    category: '现代玻璃幕墙',
    description: '高层玻璃塔楼，现代城市地标',
    icon: 'glass-tower',
    buildings: [
      {
        type: 'stepped',
        params: {
          baseWidth: 35,
          baseDepth: 35,
          levels: 4,
          stepback: 5,
          levelHeight: 30,
        },
        position: [0, 0],
        rotation: 0,
        color: '#3498DB',
      },
    ],
  },
  {
    id: 'modern-glass-complex',
    name: '玻璃幕墙建筑群',
    category: '现代玻璃幕墙',
    description: '多栋玻璃幕墙建筑组成的建筑群',
    icon: 'glass-complex',
    buildings: [
      {
        type: 'box',
        params: { width: 25, depth: 25, height: 60 },
        position: [0, 0],
        rotation: 0,
        color: '#5DADE2',
      },
      {
        type: 'box',
        params: { width: 20, depth: 20, height: 45 },
        position: [35, 15],
        rotation: 0,
        color: '#85C1E9',
      },
      {
        type: 'box',
        params: { width: 18, depth: 18, height: 35 },
        position: [-30, -20],
        rotation: 0,
        color: '#AED6F1',
      },
      {
        type: 'box',
        params: { width: 22, depth: 22, height: 50 },
        position: [25, -25],
        rotation: 0,
        color: '#5DADE2',
      },
    ],
  },
  {
    id: 'residential-mid-rise',
    name: '多层住宅楼',
    category: '住宅标准层',
    description: '6层板式住宅楼，一梯两户',
    icon: 'residential',
    buildings: [
      {
        type: 'box',
        params: { width: 40, depth: 12, height: 18 },
        position: [0, 0],
        rotation: 0,
        color: '#F5B041',
      },
      {
        type: 'box',
        params: { width: 10, depth: 4, height: 3 },
        position: [-12, -6],
        rotation: 0,
        color: '#D4AC0D',
      },
      {
        type: 'box',
        params: { width: 10, depth: 4, height: 3 },
        position: [12, -6],
        rotation: 0,
        color: '#D4AC0D',
      },
    ],
  },
  {
    id: 'residential-high-rise',
    name: '高层住宅楼',
    category: '住宅标准层',
    description: '20层高层住宅楼，塔式设计',
    icon: 'residential-high',
    buildings: [
      {
        type: 'box',
        params: { width: 25, depth: 25, height: 60 },
        position: [0, 0],
        rotation: 0,
        color: '#EB984E',
      },
      {
        type: 'box',
        params: { width: 8, depth: 4, height: 3 },
        position: [0, -12.5],
        rotation: 0,
        color: '#D4AC0D',
      },
    ],
  },
  {
    id: 'residential-complex',
    name: '住宅小区',
    category: '住宅标准层',
    description: '多栋住宅楼组成的住宅小区',
    icon: 'residential-complex',
    buildings: [
      {
        type: 'box',
        params: { width: 35, depth: 12, height: 24 },
        position: [0, 0],
        rotation: 0,
        color: '#F5B041',
      },
      {
        type: 'box',
        params: { width: 35, depth: 12, height: 24 },
        position: [0, 40],
        rotation: 0,
        color: '#EB984E',
      },
      {
        type: 'box',
        params: { width: 35, depth: 12, height: 18 },
        position: [0, -40],
        rotation: 0,
        color: '#F8C471',
      },
      {
        type: 'box',
        params: { width: 20, depth: 10, height: 12 },
        position: [60, 0],
        rotation: 0,
        color: '#D4AC0D',
      },
      {
        type: 'road',
        params: { length: 150, width: 8 },
        position: [30, 0],
        rotation: 90,
        color: '#708090',
      },
      {
        type: 'green-belt',
        params: { length: 80, width: 6, height: 1 },
        position: [0, 20],
        rotation: 0,
        color: '#4CAF50',
      },
      {
        type: 'green-belt',
        params: { length: 80, width: 6, height: 1 },
        position: [0, -20],
        rotation: 0,
        color: '#4CAF50',
      },
    ],
  },
  {
    id: 'residential-apartment-l-shape',
    name: 'L形住宅楼',
    category: '住宅标准层',
    description: 'L形布局的住宅楼，转角设计',
    icon: 'residential-l',
    buildings: [
      {
        type: 'l-shape',
        params: {
          wing1Length: 35,
          wing2Length: 30,
          width: 10,
          height: 21,
        },
        position: [0, 0],
        rotation: 0,
        color: '#F5B041',
      },
    ],
  },
  {
    id: 'basketball-court-template',
    name: '标准篮球场',
    category: '体育设施',
    description: '标准尺寸篮球场，含篮架和场地线',
    icon: 'basketball-court',
    buildings: [
      {
        type: 'basketball-court',
        params: {
          length: 28,
          width: 15,
          floorThickness: 0.2,
          poleHeight: 4,
          backboardWidth: 1.8,
          backboardHeight: 1.05,
        },
        position: [0, 0],
        rotation: 0,
        color: '#D2B48C',
      },
    ],
  },
  {
    id: 'football-field-template',
    name: '标准足球场',
    category: '体育设施',
    description: '标准尺寸足球场，含球门和场地线',
    icon: 'football-field',
    buildings: [
      {
        type: 'football-field',
        params: {
          length: 105,
          width: 68,
          floorThickness: 0.2,
          goalHeight: 2.44,
          goalWidth: 7.32,
        },
        position: [0, 0],
        rotation: 0,
        color: '#228B22',
      },
    ],
  },
  {
    id: 'tennis-court-template',
    name: '标准网球场',
    category: '体育设施',
    description: '标准尺寸网球场，含球网和场地线',
    icon: 'tennis-court',
    buildings: [
      {
        type: 'tennis-court',
        params: {
          length: 23.77,
          width: 10.97,
          singleWidth: 8.23,
          floorThickness: 0.2,
          netHeight: 0.914,
        },
        position: [0, 0],
        rotation: 0,
        color: '#4169E1',
      },
    ],
  },
  {
    id: 'gymnasium-template',
    name: '综合体育馆',
    category: '体育设施',
    description: '大型综合体育馆，含室内场地和看台',
    icon: 'gymnasium',
    buildings: [
      {
        type: 'gymnasium',
        params: {
          length: 80,
          width: 60,
          height: 25,
          wallThickness: 1.5,
          roofHeight: 12,
          entranceWidth: 12,
          entranceHeight: 6,
        },
        position: [0, 0],
        rotation: 0,
        color: '#F5F5DC',
      },
    ],
  },
]

export function getTemplatesByCategory(): Record<string, BuildingTemplate[]> {
  const result: Record<string, BuildingTemplate[]> = {}
  for (const template of BUILDING_TEMPLATES) {
    if (!result[template.category]) {
      result[template.category] = []
    }
    result[template.category].push(template)
  }
  return result
}
